name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6.3

      - name: Setup Scala CLI
        uses: VirtusLab/scala-cli-setup@main

      - name: Run changelog tests
        run: scala-cli test changelog

      - name: Check changelog compliance
        run: scala-cli changelog

      - name: Install libidn2-dev libcurl3-dev for sttp on Native
        run: |
          sudo apt-get update
          sudo apt-get install libidn2-dev libcurl3-dev

      - name: Run cross-platform tests
        run: scala-cli test tests/CrossPlatform.test.scala
      
      - name: Compile and run examples
        run: |
          cd examples
          for file in *.sc
          do
            scala-cli "$file"
          done

      - name: Compile and test examples
        run: |
          cd examples
          for file in *.test.scala
          do
            scala-cli test "$file"
          done
